---
 - hosts:  all
   become: true
   remote_user: ec2-user
   tasks:
   - name: Remove nginx
     ansible.builtin.package:
      name: nginx
      state: absent
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started