---
 - hosts: Frontend
   become: true
   remote_user: ec2-user
  
   tasks:
    - name: Disable the nginx module
      ansible.builtin.command:
        cmd: dnf module disable nginx -y
       
    - name: Enable the ngix module
      ansible.builtin.command:
        cmd: dnf module enable nginx:1.24 -y
       

